name: Release nPaper

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build nPaper
      run: mvn clean install
    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
        files: ./nPaper-Server/target/npaper-1.7.10-R0.1-SNAPSHOT.jar